services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    expose:
      - 5678
    volumes:
      - ./n8n_data:/home/node/.n8n

  nginx:
    image: nginx:latest
    container_name: nginx-n8n
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - n8n

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-n8n
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - n8n

  backup:
    build:
      context: cron
      dockerfile: Dockerfile
    container_name: backup-n8n
    restart: always
    environment:
      - BACKUP_NAME=${BACKUP_NAME}
      - S3_BUCKET_URL=${S3_BUCKET_URL}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./n8n_data:/data:ro
    depends_on:
      - n8n
